[package]
name = "bulletproofs-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# arkworks
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-pallas = { workspace = true }
ark-vesta = { workspace = true }
ark-bn254 = { workspace = true }
ark-std = { workspace = true }

# napi
napi = { workspace = true }
napi-derive = { workspace = true }

# random
rand = { workspace = true }
rand_chacha = { workspace = true }

# bulletproofs
bulletproofs = { workspace = true }
spongefish = { workspace = true }

# curves-napi for field element types
curves-napi = { workspace = true }


[build-dependencies]
napi-build = { workspace = true }