[package]
name = "curves-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[build-dependencies]
napi-build = { workspace = true }

[dependencies]
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-pallas = { workspace = true, optional = true }
ark-vesta = { workspace = true, optional = true }
mina-curves = { workspace = true, optional = true }
ark-bn254 = { workspace = true }
ark-std = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true }
num-bigint = { workspace = true }
num-integer = { workspace = true }

[features]
default = ["arkworks"]
arkworks = ["ark-pallas", "ark-vesta"]
mina-curves-backend = ["mina-curves"]

[dev-dependencies]
proptest = { workspace = true }
