[package]
name = "curves-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pallas"]
pallas = ["ark-pallas"]
vesta = ["ark-vesta"]
bn254 = ["ark-bn254"]

[build-dependencies]
napi-build = "2.2.4"

[dependencies]
ark-ff = { version = "0.5.0" }
ark-pallas = { version = "0.5.0", optional = true }
ark-vesta = { version = "0.5.0", optional = true }
ark-bn254 = { version = "0.5.0", optional = true }
ark-std = { version = "0.5.0" }
rand = { version = "0.8", features = ["std_rng"] }
napi = { version = "3.4.0", features = ["napi4"] }
napi-derive = "3.3.0"

[profile.release]
opt-level = "s"
lto = true
