[package]
name = "curves-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[build-dependencies]
napi-build = "2.2.4"

[dependencies]
ark-ff = { version = "0.5.0" }
ark-pallas = { version = "0.5.0" }
ark-vesta = { version = "0.5.0" }
ark-bn254 = { version = "0.5.0" }
ark-std = { version = "0.5.0" }
rand = { version = "0.8", features = ["std_rng"] }
rand_chacha = { version = "0.3" }
napi = { version = "3.4.0", features = ["napi6"] }
napi-derive = "3.3.0"
num-bigint = "0.4.4"
num-integer = "0.1"

[dev-dependencies]
proptest = "1.0"

[profile.release]
opt-level = "s"
lto = true
